[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  functionsPort = 8888

[[redirects]]
  from = "/api/widgets"
  to = "/.netlify/functions/widgets"
  status = 200
  force = true

[[redirects]]
  from = "/api/widgets/*"
  to = "/.netlify/functions/widgets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18" 